# Usa una imagen base de Node.js LTS
FROM node:20-alpine

# Define el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de definición de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código del backend (incluyendo server.js)
COPY . .

# Expone el puerto de la API
EXPOSE 3000